apiVersion: v1
kind: Service
metadata:
  name: {{ template "dremio.coordinator.fullname" . }}
  labels:
    app: {{ template "dremio.name" . }}
    chart: {{ template "dremio.chart" . }}
    component: "{{ .Values.coordinator.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.coordinator.client.port | default 31010 }}
    targetPort: 31010
    name: client
  - port: {{ .Values.coordinator.web.port | default 9047 }}
    targetPort: 9047
    name: web
  selector:
    app: {{ template "dremio.name" . }}
    component: "{{ .Values.coordinator.name }}"
    release: {{ .Release.Name }}
  type: {{ .Values.serviceType | default "NodePort" }}
  sessionAffinity: ClientIP
